//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FICTFeed.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FICTFeed.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тестовий рядок.
        /// </summary>
        internal static string _TestString {
            get {
                return ResourceManager.GetString("_TestString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додати новину.
        /// </summary>
        internal static string AddNewsItem {
            get {
                return ResourceManager.GetString("AddNewsItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всі новини.
        /// </summary>
        internal static string AllNews {
            get {
                return ResourceManager.GetString("AllNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Користувач з такою адресою вже зареєстрованний..
        /// </summary>
        internal static string AlreadyRegistered {
            get {
                return ResourceManager.GetString("AlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Підтвердження паролю.
        /// </summary>
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Створити.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Створити группу.
        /// </summary>
        internal static string CreateGroup {
            get {
                return ResourceManager.GetString("CreateGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зараз неділя №{0}.
        /// </summary>
        internal static string CurrentWeekNo {
            get {
                return ResourceManager.GetString("CurrentWeekNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поля &quot;{0}&quot; та &quot;{1}&quot; повинні співпадати..
        /// </summary>
        internal static string CustomizebleCompareErrorMessage {
            get {
                return ResourceManager.GetString("CustomizebleCompareErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &quot;{0}&quot; має бути заповнене..
        /// </summary>
        internal static string CustomizebleRequiredErrorMessage {
            get {
                return ResourceManager.GetString("CustomizebleRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &quot;{0}&quot; має бути не довше ніж {1}, та не менше ніж {2} символів..
        /// </summary>
        internal static string CustomizebleStringLengthErrorMessage {
            get {
                return ResourceManager.GetString("CustomizebleStringLengthErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to День.
        /// </summary>
        internal static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Деталі.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редагувати.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редагування группи.
        /// </summary>
        internal static string EditGroup {
            get {
                return ResourceManager.GetString("EditGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Такої сторінки не існує. =(.
        /// </summary>
        internal static string Error404 {
            get {
                return ResourceManager.GetString("Error404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;card hoverable&quot;&gt;
        ///                &lt;div class=&quot;card-image&quot;&gt;
        ///                    &lt;h3&gt;Відновлення паролю&lt;/h3&gt;
        ///                &lt;/div&gt;
        ///                &lt;div class=&quot;card-content&quot;&gt;
        ///                    	&lt;p&gt;Шановний {0}!&lt;br/&gt;
        ///			Тільки що був запит на відновлення паролю до вашого аккаунту на FICT Feed.&lt;br/&gt;
        ///			Якщо це були не ви -- проігноруйте цей лист.&lt;br/&gt;
        ///			З повагою, команда FICT Feed.&lt;br/&gt;
        ///			&lt;/p&gt;
        ///                &lt;/div&gt;
        ///                &lt;div class=&quot;card-action light&quot;&gt;
        ///			Для того щоб вста [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ForgotMailTemplate {
            get {
                return ResourceManager.GetString("ForgotMailTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;style&gt;
        ///div {
        ///    padding: 0.5em;
        ///}
        ///.card .card-image {
        ///    position: relative;
        ///}
        ///h3 {
        ///    padding-top: 15px;
        ///    font-size: 2.92rem;
        ///    line-height: 3.212rem;
        ///    margin: 1.46rem 0 1.168rem 0;
        ///    margin-top: 0;
        ///}
        ///.card {
        ///    display: inline-block;
        ///    position: relative;
        ///    overflow: hidden;
        ///    margin: 0.5rem 0 1rem 0;
        ///    background-color: #fff;
        ///    border-radius: 2px;
        ///}
        ///.card-content {
        ///    padding: 20px;
        ///    border-radius: 0 0 2px 2px;
        ///}
        ///.card-action {
        ///    border-top: 1px s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ForgotMailTemplateStyle {
            get {
                return ResourceManager.GetString("ForgotMailTemplateStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Забув пароль?.
        /// </summary>
        internal static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відновлення паролю.
        /// </summary>
        internal static string ForgotPasswordPage {
            get {
                return ResourceManager.GetString("ForgotPasswordPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завантажити повну версію.
        /// </summary>
        internal static string GetFullSchedule {
            get {
                return ResourceManager.GetString("GetFullSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загальна.
        /// </summary>
        internal static string Global {
            get {
                return ResourceManager.GetString("Global", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Группи.
        /// </summary>
        internal static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Розклад.
        /// </summary>
        internal static string GroupSchedule {
            get {
                return ResourceManager.GetString("GroupSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Головна.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невірний email або пароль.
        /// </summary>
        internal static string InvalidMailOrPass {
            get {
                return ResourceManager.GetString("InvalidMailOrPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пара.
        /// </summary>
        internal static string Lesson {
            get {
                return ResourceManager.GetString("Lesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Розклад.
        /// </summary>
        internal static string Lessons {
            get {
                return ResourceManager.GetString("Lessons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вхід.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вихід.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Електрона адреса.
        /// </summary>
        internal static string Mail {
            get {
                return ResourceManager.GetString("Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лист з інструкціями надіслано.
        /// </summary>
        internal static string MailSent {
            get {
                return ResourceManager.GetString("MailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ім&apos;я.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Свіжі новини.
        /// </summary>
        internal static string NewestNews {
            get {
                return ResourceManager.GetString("NewestNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відображення новин: .
        /// </summary>
        internal static string NewsFilters {
            get {
                return ResourceManager.GetString("NewsFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новини для {0}.
        /// </summary>
        internal static string NewsFor {
            get {
                return ResourceManager.GetString("NewsFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Створення новини.
        /// </summary>
        internal static string NewsItemCreate {
            get {
                return ResourceManager.GetString("NewsItemCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На жаль, новин немає =(.
        /// </summary>
        internal static string NoNews {
            get {
                return ResourceManager.GetString("NoNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль успішно оновлено..
        /// </summary>
        internal static string PasswordUpdated {
            get {
                return ResourceManager.GetString("PasswordUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Читати далі.
        /// </summary>
        internal static string ReadMore {
            get {
                return ResourceManager.GetString("ReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Реєстрація.
        /// </summary>
        internal static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Роль.
        /// </summary>
        internal static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зберегти.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коментувати.
        /// </summary>
        internal static string SendComment {
            get {
                return ResourceManager.GetString("SendComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відновити.
        /// </summary>
        internal static string SendPass2Mail {
            get {
                return ResourceManager.GetString("SendPass2Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опис.
        /// </summary>
        internal static string ShortDescription {
            get {
                return ResourceManager.GetString("ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FICT Feed.
        /// </summary>
        internal static string SiteTitle {
            get {
                return ResourceManager.GetString("SiteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заголовок.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Користувачі.
        /// </summary>
        internal static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неділя.
        /// </summary>
        internal static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }
    }
}
