//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FICTFeed.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FICTFeed.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тестовий рядок.
        /// </summary>
        internal static string _TestString {
            get {
                return ResourceManager.GetString("_TestString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додати новину.
        /// </summary>
        internal static string AddNewsItem {
            get {
                return ResourceManager.GetString("AddNewsItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адміністратор.
        /// </summary>
        internal static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всі групи.
        /// </summary>
        internal static string AllGroups {
            get {
                return ResourceManager.GetString("AllGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всі новини.
        /// </summary>
        internal static string AllNews {
            get {
                return ResourceManager.GetString("AllNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всі користувачі.
        /// </summary>
        internal static string AllUsers {
            get {
                return ResourceManager.GetString("AllUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Користувач з такою адресою вже зареєстрованний..
        /// </summary>
        internal static string AlreadyRegistered {
            get {
                return ResourceManager.GetString("AlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Підтвердження паролю.
        /// </summary>
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Створити.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Створити группу.
        /// </summary>
        internal static string CreateGroup {
            get {
                return ResourceManager.GetString("CreateGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зараз неділя №{0}.
        /// </summary>
        internal static string CurrentWeekNo {
            get {
                return ResourceManager.GetString("CurrentWeekNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поля &quot;{0}&quot; та &quot;{1}&quot; повинні співпадати..
        /// </summary>
        internal static string CustomizebleCompareErrorMessage {
            get {
                return ResourceManager.GetString("CustomizebleCompareErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &quot;{0}&quot; має бути заповнене..
        /// </summary>
        internal static string CustomizebleRequiredErrorMessage {
            get {
                return ResourceManager.GetString("CustomizebleRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &quot;{0}&quot; має бути не довше ніж {1}, та не менше ніж {2} символів..
        /// </summary>
        internal static string CustomizebleStringLengthErrorMessage {
            get {
                return ResourceManager.GetString("CustomizebleStringLengthErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to День.
        /// </summary>
        internal static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Деталі.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редагувати.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редагування группи.
        /// </summary>
        internal static string EditGroup {
            get {
                return ResourceManager.GetString("EditGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Такої сторінки не існує. =(.
        /// </summary>
        internal static string Error404 {
            get {
                return ResourceManager.GetString("Error404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завантажити повну версію.
        /// </summary>
        internal static string GetFullSchedule {
            get {
                return ResourceManager.GetString("GetFullSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загальна.
        /// </summary>
        internal static string Global {
            get {
                return ResourceManager.GetString("Global", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Группи.
        /// </summary>
        internal static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Розклад.
        /// </summary>
        internal static string GroupSchedule {
            get {
                return ResourceManager.GetString("GroupSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Головна.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невірний email або пароль.
        /// </summary>
        internal static string InvalidMailOrPass {
            get {
                return ResourceManager.GetString("InvalidMailOrPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пара.
        /// </summary>
        internal static string Lesson {
            get {
                return ResourceManager.GetString("Lesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Розклад.
        /// </summary>
        internal static string Lessons {
            get {
                return ResourceManager.GetString("Lessons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вхід.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вихід.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Електронна адресса.
        /// </summary>
        internal static string Mail {
            get {
                return ResourceManager.GetString("Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Модератор.
        /// </summary>
        internal static string Moderator {
            get {
                return ResourceManager.GetString("Moderator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ім&apos;я.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Свіжі новини.
        /// </summary>
        internal static string NewestNews {
            get {
                return ResourceManager.GetString("NewestNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відображення новин: .
        /// </summary>
        internal static string NewsFilters {
            get {
                return ResourceManager.GetString("NewsFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новини для {0}.
        /// </summary>
        internal static string NewsFor {
            get {
                return ResourceManager.GetString("NewsFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Створення новини.
        /// </summary>
        internal static string NewsItemCreate {
            get {
                return ResourceManager.GetString("NewsItemCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На жаль, новин немає =(.
        /// </summary>
        internal static string NoNews {
            get {
                return ResourceManager.GetString("NoNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Староста.
        /// </summary>
        internal static string Praepostor {
            get {
                return ResourceManager.GetString("Praepostor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Читати далі.
        /// </summary>
        internal static string ReadMore {
            get {
                return ResourceManager.GetString("ReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Реєстрація.
        /// </summary>
        internal static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Роль.
        /// </summary>
        internal static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зберегти.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коментувати.
        /// </summary>
        internal static string SendComment {
            get {
                return ResourceManager.GetString("SendComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опис.
        /// </summary>
        internal static string ShortDescription {
            get {
                return ResourceManager.GetString("ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FICT Feed.
        /// </summary>
        internal static string SiteTitle {
            get {
                return ResourceManager.GetString("SiteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заголовок.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Студент.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Користувачі.
        /// </summary>
        internal static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неділя.
        /// </summary>
        internal static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }
    }
}
